global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.example.com:587"
  smtp_from: "alertmanager@example.com"
  smtp_auth_username: "your_username"
  smtp_auth_password: "your_password"
  slack_api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: default-receiver
  routes:
    - match:
        severity: critical
      receiver: critical-receiver

receivers:
  - name: default-receiver
    email_configs:
      - to: "team@example.com"
    slack_configs:
      - channel: "#alerts"
        send_resolved: true

  - name: critical-receiver
    email_configs:
      - to: "oncall@example.com"
    slack_configs:
      - channel: "#critical-alerts"
        send_resolved: true
