version: "3.8"
services:
  kong:
    image: kong:latest
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/kong.yml
      - KONG_JWT_SECRET=${KONG_JWT_SECRET}
    volumes:
      - ./gateway/kong/kong.yml:/kong/kong.yml
      - ./gateway/kong/plugins:/kong/plugins
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - observashop-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - observashop-network
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - ./minio/minio-config.yaml:/etc/minio/config.yaml
      - minio-data:/data
    networks:
      - observashop-network
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - observashop-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    networks:
      - observashop-network
  postgres-auth:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_AUTH_USER}
      - POSTGRES_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRES_DB=auth_db
    volumes:
      - ./databases/auth/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-auth-data:/var/lib/postgresql/data
    networks:
      - observashop-network
  postgres-authz:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_AUTHZ_USER}
      - POSTGRES_PASSWORD=${POSTGRES_AUTHZ_PASSWORD}
      - POSTGRES_DB=authz_db
    volumes:
      - ./databases/authz/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-authz-data:/var/lib/postgresql/data
    networks:
      - observashop-network
  postgres-product:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_PRODUCT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PRODUCT_PASSWORD}
      - POSTGRES_DB=product_db
    volumes:
      - ./databases/product/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-product-data:/var/lib/postgresql/data
    networks:
      - observashop-network
  postgres-order:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_ORDER_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ORDER_PASSWORD}
      - POSTGRES_DB=order_db
    volumes:
      - ./databases/order/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-order-data:/var/lib/postgresql/data
    networks:
      - observashop-network
  postgres-payment:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_PAYMENT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PAYMENT_PASSWORD}
      - POSTGRES_DB=payment_db
    volumes:
      - ./databases/payment/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-payment-data:/var/lib/postgresql/data
    networks:
      - observashop-network
  postgres-notification:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_NOTIFICATION_USER}
      - POSTGRES_PASSWORD=${POSTGRES_NOTIFICATION_PASSWORD}
      - POSTGRES_DB=notification_db
    volumes:
      - ./databases/notification/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-notification-data:/var/lib/postgresql/data
    networks:
      - observashop-network
  postgres-media:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_MEDIA_USER}
      - POSTGRES_PASSWORD=${POSTGRES_MEDIA_PASSWORD}
      - POSTGRES_DB=media_db
    volumes:
      - ./databases/media/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-media-data:/var/lib/postgresql/data
    networks:
      - observashop-network
  postgres-analytics:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_ANALYTICS_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ANALYTICS_PASSWORD}
      - POSTGRES_DB=analytics_db
    volumes:
      - ./databases/analytics/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-analytics-data:/var/lib/postgresql/data
    networks:
      - observashop-network
volumes:
  redis-data:
  minio-data:
  kafka-data:
  zookeeper-data:
  postgres-auth-data:
  postgres-authz-data:
  postgres-product-data:
  postgres-order-data:
  postgres-payment-data:
  postgres-notification-data:
  postgres-media-data:
  postgres-analytics-data:
networks:
  observashop-network:
    driver: bridge
