services:
  analytics-service:
    build:
      context: ../
      dockerfile: infra/docker/analytics_service.Dockerfile
    environment:
      - POSTGRES_HOST=postgres-analytics
      - POSTGRES_USER=${POSTGRES_ANALYTICS_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ANALYTICS_PASSWORD}
      - POSTGRES_DB=analytics
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=your-service-name
      - OTEL_PYTHON_LOG_CORRELATION=true
    env_file: .env
    ports:
      - "8017:8000"
    networks:
      - observashop-network
  auth-service:
    build:
      context: ../
      dockerfile: infra/docker/auth_service.Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_HOST=postgres-auth
      - POSTGRES_USER=${POSTGRES_AUTH_USER}
      - POSTGRES_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRES_DB=auth
      - ENV=development
      - CONSOLE_LOG_LEVEL=DEBUG
      - FILE_LOG_LEVEL=DEBUG
      - ERROR_LOG_LEVEL=ERROR
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=your-service-name
      - OTEL_PYTHON_LOG_CORRELATION=true

    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8010:8000"
    networks:
      - observashop-network
  authz-service:
    build:
      context: ../
      dockerfile: infra/docker/authz_service.Dockerfile
    environment:
      - POSTGRES_HOST=postgres-authz
      - POSTGRES_USER=${POSTGRES_AUTHZ_USER}
      - POSTGRES_PASSWORD=${POSTGRES_AUTHZ_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - POSTGRES_DB=authz
      - ENV=development
      - CONSOLE_LOG_LEVEL=DEBUG
      - FILE_LOG_LEVEL=DEBUG
      - ERROR_LOG_LEVEL=ERROR
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=your-service-name
      - OTEL_PYTHON_LOG_CORRELATION=true
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8011:8000"
    networks:
      - observashop-network
  product-service:
    build:
      context: ../
      dockerfile: infra/docker/product_service.Dockerfile
    environment:
      - POSTGRES_HOST=postgres-product
      - POSTGRES_USER=${POSTGRES_PRODUCT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PRODUCT_PASSWORD}
      - POSTGRES_DB=product
      - REDIS_HOST=${REDIS_HOST}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=your-service-name
      - OTEL_PYTHON_LOG_CORRELATION=true
    env_file: .env
    ports:
      - "8012:8000"
    networks:
      - observashop-network
  order-service:
    build:
      context: ../
      dockerfile: infra/docker/order_service.Dockerfile
    environment:
      - POSTGRES_HOST=postgres-order
      - POSTGRES_USER=${POSTGRES_ORDER_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ORDER_PASSWORD}
      - POSTGRES_DB=orders
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=your-service-name
      - OTEL_PYTHON_LOG_CORRELATION=true
    env_file: .env
    ports:
      - "8013:8000"
    networks:
      - observashop-network
  payment-service:
    build:
      context: ../
      dockerfile: infra/docker/payment_service.Dockerfile
    environment:
      - POSTGRES_HOST=postgres-payment
      - POSTGRES_USER=${POSTGRES_PAYMENT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PAYMENT_PASSWORD}
      - POSTGRES_DB=payment
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=your-service-name
      - OTEL_PYTHON_LOG_CORRELATION=true
    env_file: .env
    ports:
      - "8014:8000"
    networks:
      - observashop-network
  notification-service:
    build:
      context: ../
      dockerfile: infra/docker/notification_service.Dockerfile
    environment:
      - POSTGRES_HOST=postgres-notification
      - POSTGRES_USER=${POSTGRES_NOTIFICATION_USER}
      - POSTGRES_PASSWORD=${POSTGRES_NOTIFICATION_PASSWORD}
      - POSTGRES_DB=notification
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=your-service-name
      - OTEL_PYTHON_LOG_CORRELATION=true
    env_file: .env
    ports:
      - "8016:8000"
    networks:
      - observashop-network
  media-service:
    build:
      context: ../
      dockerfile: infra/docker/media_service.Dockerfile
    environment:
      - POSTGRES_HOST=postgres-media
      - POSTGRES_USER=${POSTGRES_MEDIA_USER}
      - POSTGRES_PASSWORD=${POSTGRES_MEDIA_PASSWORD}
      - POSTGRES_DB=media
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=your-service-name
      - OTEL_PYTHON_LOG_CORRELATION=true
    env_file: .env
    ports:
      - "8015:8000"
    networks:
      - observashop-network
networks:
  observashop-network:
    driver: bridge
