"""Initial schema

Revision ID: 1f9de611060d
Revises:
Create Date: 2025-07-22 13:13:31.360384

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f9de611060d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("owner_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="media",
    )
    op.create_index(
        op.f("ix_media_media_id"), "media", ["id"], unique=False, schema="media"
    )
    op.create_index(
        op.f("ix_media_media_owner_id"),
        "media",
        ["owner_id"],
        unique=False,
        schema="media",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_media_owner_id"), table_name="media", schema="media")
    op.drop_index(op.f("ix_media_media_id"), table_name="media", schema="media")
    op.drop_table("media", schema="media")
    # ### end Alembic commands ###
