"""update media database

Revision ID: 39c289c82d94
Revises: 1f9de611060d
Create Date: 2025-08-13 15:03:11.552841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '39c289c82d94'
down_revision: Union[str, Sequence[str], None] = '1f9de611060d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False), schema='media')
    op.add_column('media', sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False), schema='media')
    op.add_column('media', sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False), schema='media')
    op.add_column('media', sa.Column('file_size', sa.Integer(), nullable=False), schema='media')
    op.add_column('media', sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False), schema='media')
    op.add_column('media', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False), schema='media')
    op.add_column('media', sa.Column('is_active', sa.Boolean(), nullable=False), schema='media')
    op.drop_column('media', 'url', schema='media')
    op.drop_column('media', 'type', schema='media')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False), schema='media')
    op.add_column('media', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='media')
    op.drop_column('media', 'is_active', schema='media')
    op.drop_column('media', 'updated_at', schema='media')
    op.drop_column('media', 'storage_key', schema='media')
    op.drop_column('media', 'file_size', schema='media')
    op.drop_column('media', 'file_type', schema='media')
    op.drop_column('media', 'media_type', schema='media')
    op.drop_column('media', 'filename', schema='media')
    # ### end Alembic commands ###
