global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # --- APPLICATION SERVICES ---
  - job_name: "fastapi-services"
    static_configs:
      - targets:
          - "auth-service:8010"
          - "authz-service:8011"
          - "product-service:8012"
          - "order-service:8013"
          - "payment-service:8014"
          - "media-service:8015"
          - "notification-service:8016"
          - "analytics-service:8017"
        labels:
          group: "services"
    metrics_path: /metrics
    scrape_interval: 10s

  # --- OBSERVABILITY TOOLS ---
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          group: "observability"

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]
        labels:
          group: "observability"

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
        labels:
          group: "observability"
    metrics_path: /metrics

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
        labels:
          group: "observability"
    metrics_path: /metrics

  # --- INFRASTRUCTURE MONITORING ---
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          group: "infrastructure"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          group: "infrastructure"
    scrape_interval: 10s

  # --- DATABASE MONITORING ---
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          group: "databases"

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          group: "databases"

  # --- KAFKA ---
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]
        labels:
          group: "messaging"

  # --- KONG API GATEWAY ---
  - job_name: "kong"
    static_configs:
      - targets: ["kong:8001"]
        labels:
          group: "gateway"
    metrics_path: /metrics

  # --- MINIO ---
  - job_name: "minio"
    static_configs:
      - targets: ["minio:9000"]
        labels:
          group: "storage"
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    basic_auth:
      username: "${MINIO_ROOT_USER}"
      password: "${MINIO_ROOT_PASSWORD}"

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alert-manager:9093"]
