"""Initial schema

Revision ID: e878a73fd63e
Revises:
Create Date: 2025-07-22 14:45:16.802791

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e878a73fd63e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("total", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="orders",
    )
    op.create_index(
        op.f("ix_orders_orders_id"), "orders", ["id"], unique=False, schema="orders"
    )
    op.create_index(
        op.f("ix_orders_orders_user_id"),
        "orders",
        ["user_id"],
        unique=False,
        schema="orders",
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="orders",
    )
    op.create_index(
        op.f("ix_orders_order_items_order_id"),
        "order_items",
        ["order_id"],
        unique=False,
        schema="orders",
    )
    op.create_index(
        op.f("ix_orders_order_items_product_id"),
        "order_items",
        ["product_id"],
        unique=False,
        schema="orders",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_orders_order_items_product_id"),
        table_name="order_items",
        schema="orders",
    )
    op.drop_index(
        op.f("ix_orders_order_items_order_id"),
        table_name="order_items",
        schema="orders",
    )
    op.drop_table("order_items", schema="orders")
    op.drop_index(
        op.f("ix_orders_orders_user_id"), table_name="orders", schema="orders"
    )
    op.drop_index(op.f("ix_orders_orders_id"), table_name="orders", schema="orders")
    op.drop_table("orders", schema="orders")
    # ### end Alembic commands ###
