"""Initial schema

Revision ID: 1c8f889f8695
Revises: 
Create Date: 2025-07-22 15:00:23.067319

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c8f889f8695'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='payment'
    )
    op.create_index(op.f('ix_payment_payments_id'), 'payments', ['id'], unique=False, schema='payment')
    op.create_index(op.f('ix_payment_payments_order_id'), 'payments', ['order_id'], unique=False, schema='payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_payments_order_id'), table_name='payments', schema='payment')
    op.drop_index(op.f('ix_payment_payments_id'), table_name='payments', schema='payment')
    op.drop_table('payments', schema='payment')
    # ### end Alembic commands ###
