"""add fields to payment table

Revision ID: 3ecb46a4529c
Revises: 1c8f889f8695
Create Date: 2025-08-10 06:11:51.988788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3ecb46a4529c'
down_revision: Union[str, Sequence[str], None] = '1c8f889f8695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False), schema='payment')
    op.add_column('payments', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False), schema='payment')
    op.add_column('payments', sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True), schema='payment')
    op.add_column('payments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False), schema='payment')
    op.add_column('payments', sa.Column('is_active', sa.Boolean(), nullable=False), schema='payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'is_active', schema='payment')
    op.drop_column('payments', 'updated_at', schema='payment')
    op.drop_column('payments', 'transaction_id', schema='payment')
    op.drop_column('payments', 'payment_method', schema='payment')
    op.drop_column('payments', 'currency', schema='payment')
    # ### end Alembic commands ###
