{
 "title": "Service Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Application Name",
    "query": {
     "query": "label_values(http_requests_total, instance)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate(RPS)",
   "type": "stat",
   "description": "Shows how fast the system is processing requests right now (requests per second). Helps identify traffic spikes or slowdowns.Helps track demand on the system — e.g., daily or weekly usage volume.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{instance=~\"$instance:.*\", endpoint!=\"/metrics\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Shows how many requests were served in the selected time window. Helps stakeholders see overall demand (daily traffic, weekly usage, etc.).",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{instance=~\"$instance:.*\", endpoint!=\"/metrics\"}[$__range]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{instance=~\"$instance:.*\", endpoint!=\"/metrics\"}[$__rate_interval]))\n/\nsum(rate(http_request_duration_seconds_count{instance=~\"$instance:.*\", endpoint!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_exceptions_total{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (\n  rate(http_requests_total{instance=~\"$instance:.*\", status=~\"2..\", endpoint!=\"/metrics\"}[$__rate_interval])\n)\n/\nsum by(endpoint) (\n  rate(http_requests_total{instance=~\"$instance:.*\", endpoint!=\"/metrics\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (\n  rate(http_requests_total{instance=~\"$instance:.*\", status=~\"5..\", endpoint!=\"/metrics\"}[$__rate_interval])\n)\n/\nsum by(endpoint) (\n  rate(http_requests_total{instance=~\"$instance:.*\", endpoint!=\"/metrics\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(\n    rate(http_request_duration_seconds_bucket{instance=~\"$instance:.*\", endpoint!=\"/metrics\"}[1m])\n  ) by (endpoint, le)\n)\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "http_active_requests{instance=~\"$instance:.*\", endpoint!=\"/metrics\"}",
     "legendFormat": "{{endpoint}} {{method}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (\n  rate(http_requests_total{instance=~\"$instance:.*\", endpoint!=\"/metrics\"}[1m])\n)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service, type) (\n  rate(\n    {app=\"observashop\"}[$__range]\n    | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>] - <msg>`\n    | type != \"\"\n  )\n)"
    }
   ]
  },
  {
   "title": "Log of All FastAPI App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"observashop\", service=~\"$service\"}"
    }
   ]
  }
 ]
}