{
 "title": "Web application monitoring dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_requests_total, instance)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Service Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"fastapi-services\", instance=~\"$service:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests increase",
   "type": "stat",
   "description": "This gives the total number of HTTP requests across all matching instance labels for the given job over the time range.",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\", instance=~\"$service:.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "description": "This panel shows the overall error rate (4xx + 5xx) as a fraction of total requests for the selected service over the last 15 minutes.\n\nincrease(http_requests_total[…, status=~\"4..\"}[15m]) → number of 4xx client errors.\n\nincrease(http_requests_total[…, status=~\"5..\"}[15m]) → number of 5xx server errors.\n\nor vector(0) → ensures the query returns 0 when there are no errors, avoiding gaps.\n\nsum(…) / sum(total requests) → calculates the proportion of requests that failed.\n\nUse case:\nProvides a quick service health indicator by combining both client- and server-side errors into one metric. A rising error rate signals degraded reliability — whether from user mistakes (4xx) or internal failures (5xx).\n\nThis metric captures the overall reliability of the service, combining both client-side and server-side failures into a single error rate. Useful for SLO/SLA tracking and setting alert thresholds (e.g., “error rate > 1% for 5m”).",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(increase(http_requests_total{job=\"$job\", instance=~\"$service:.*\", status=~\"4..\"}[$__range]) or vector(0)) + sum(increase(http_requests_total{job=\"$job\",instance=~\"$service:.*\", status=~\"5..\"}[$__range]) or vector(0))) / sum(increase(http_requests_total{job=\"$job\", instance=~\"$service:.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "description": "This panel shows the average request latency across all FastAPI services during the selected dashboard time range.\n\nNumerator = total time spent handling requests.\n\nDenominator = total number of requests.\n\nDivision = average duration per request (seconds).\n\nUse case:\nHelps track general service responsiveness. Unlike percentiles (p95/p99), which expose outliers, the average latency shows whether overall performance is trending up or down. It’s most useful when combined with percentile panels for a complete latency picture.",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[$__range])) / sum(rate(http_request_duration_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "stat",
   "description": "This panel shows the number of active/in-flight HTTP requests currently being processed by the FastAPI services (excluding /metrics scraping).\n\nhttp_active_requests → tracks requests that have started but not yet finished.\n\nsum(…) → aggregates across all service instances.\n\nendpoint!=\"/metrics\" → excludes Prometheus/Grafana scraping calls so they don’t skew the results.\n\nUse case:\nThis metric highlights concurrency and load pressure on your services.\n\nA consistently high number of active requests may indicate slow handlers, blocking calls, or resource contention.\n\nSpikes can suggest traffic surges or downstream bottlenecks.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_active_requests{job=\"fastapi-services\", endpoint!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Throughput",
     "type": "timeseries",
     "description": "This panel shows the HTTP request rate (RPS) across all FastAPI services during the selected dashboard time range.\n\nUses http_requests_total, a counter of requests served.\n\nrate(…[$__range]) converts the raw counter into a per-second rate.\n\nValues represent how many requests per second are being processed.\n\nUse case:\n\nTracks traffic load hitting your services.\n\nUseful for capacity planning and identifying traffic spikes or drops.\n\nOften paired with error rate panels (4xx/5xx) to see if errors scale with traffic.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(http_requests_total{job=\"fastapi-services\", endpoint!=\"/metrics\"}[$__range])",
       "legendFormat": "{{method}}{{endpoint}}-{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request by status code",
     "type": "piechart",
     "description": "This panel shows the request rate (RPS) broken down by HTTP status code across all FastAPI services during the selected dashboard time range.\n\nGreen = successful responses (2xx).\n\nYellow = client errors (4xx).\n\nRed = server errors (5xx).\n\nUse case:\n\nQuickly spot whether errors are increasing relative to successful requests.\n\nHelps distinguish between client-side issues (4xx) and server-side failures (5xx).\n\nUseful for troubleshooting degraded service health under load.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{job=\"fastapi-services\",endpoint!=\"/metrics\"}[$__range])) by(status)",
       "legendFormat": "Status: {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Latency Percentile",
     "type": "timeseries",
     "description": "p50 (Median Latency):\nThis panel shows the median request latency across all services. 50% of requests are faster than this value, and 50% are slower. Useful for understanding the “typical” user experience.\n\np95 Latency:\nThis panel shows the 95th percentile request latency. 95% of requests complete faster, while the slowest 5% take longer. Useful for detecting performance degradation affecting a significant minority of users.\n\np99 Latency:\nThis panel shows the 99th percentile request latency. 99% of requests complete faster, with the slowest 1% being worse. Useful for identifying tail latency issues that may cause bad user experiences or trigger timeouts.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by(le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by(le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by(le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval])) by(le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Average request duration",
     "type": "timeseries",
     "description": "This panel shows the average request latency across all FastAPI services, measured over the past 1 minute.\n\nNumerator = total processing time of requests per second.\n\nDenominator = total number of requests per second.\n\nResult = average duration (seconds) per request.\n\nUse case:\n\nQuick snapshot of overall service responsiveness.\n\nComplements percentile latency metrics (p95, p99).\n\nThis panel shows the average request latency (mean) over the past 1 minute, broken down by service or instance.\n\nNumerator = total time spent serving requests.\n\nDenominator = total requests served.\n\nResult = mean latency (seconds per request).",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(http_request_duration_seconds_sum[1m])) / (rate(http_request_duration_seconds_count[1m]))",
       "legendFormat": "{{method}} {{endpoint}} {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$job\", instance=~\"$service:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"fastapi-services\", instance=~\"$service:.*\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"fastapi-services\", instance=~\"$service:.*\"}",
     "legendFormat": "Virtual memory"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "description": "This panel shows the ratio of open file descriptors to the maximum allowed for the service process.\n\nA higher ratio means the service is nearing its FD limit.\n\nWhen close to 1 (100%), the service risks FD exhaustion → can’t open new sockets/files → failures.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"fastapi-services\", instance=~\"$service:.*\"} / process_max_fds{job=\"fastapi-services\", instance=~\"$service:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}