"""Initial schema

Revision ID: 1dd5a09d4d46
Revises: 
Create Date: 2025-07-22 13:58:17.839344

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dd5a09d4d46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='notification'
    )
    op.create_index(op.f('ix_notification_notifications_id'), 'notifications', ['id'], unique=False, schema='notification')
    op.create_index(op.f('ix_notification_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='notification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_notifications_user_id'), table_name='notifications', schema='notification')
    op.drop_index(op.f('ix_notification_notifications_id'), table_name='notifications', schema='notification')
    op.drop_table('notifications', schema='notification')
    # ### end Alembic commands ###
