"""add category table

Revision ID: 98fdbda5e3c2
Revises: b34563cd68c0
Create Date: 2025-08-07 16:06:37.097106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "98fdbda5e3c2"
down_revision: Union[str, Sequence[str], None] = "b34563cd68c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["product.categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="product",
    )
    op.add_column(
        "products",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        schema="product",
    )
    op.create_foreign_key(
        None,
        "products",
        "categories",
        ["category_id"],
        ["id"],
        source_schema="product",
        referent_schema="product",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", schema="product", type_="foreignkey")
    op.drop_column("products", "category_id", schema="product")
    op.drop_table("categories", schema="product")
    # ### end Alembic commands ###
