"""add is_active field to product model

Revision ID: 9a621b6450ee
Revises: dbd6803d5a36
Create Date: 2025-08-08 18:37:46.162830

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9a621b6450ee"
down_revision: Union[str, Sequence[str], None] = "dbd6803d5a36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("is_active", sa.Boolean(), nullable=True),
        schema="product",
    )
    op.alter_column(
        "products",
        "description",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
        existing_nullable=True,
        schema="product",
    )
    op.alter_column(
        "products",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema="product",
    )
    op.alter_column(
        "products",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        schema="product",
    )
    op.drop_index(
        op.f("ix_product_products_id"), table_name="products", schema="product"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_product_products_id"),
        "products",
        ["id"],
        unique=False,
        schema="product",
    )
    op.alter_column(
        "products",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        schema="product",
    )
    op.alter_column(
        "products",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        schema="product",
    )
    op.alter_column(
        "products",
        "description",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
        type_=sa.TEXT(),
        existing_nullable=True,
        schema="product",
    )
    op.drop_column("products", "is_active", schema="product")
    # ### end Alembic commands ###
