"""update analytics database

Revision ID: 70bff5abd95d
Revises: d56359dea888
Create Date: 2025-08-23 16:36:19.970282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70bff5abd95d'
down_revision: Union[str, Sequence[str], None] = 'd56359dea888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('metric_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False), schema='analytics')
    op.create_index(op.f('ix_analytics_metrics_created_at'), 'metrics', ['created_at'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_metrics_metric_type'), 'metrics', ['metric_type'], unique=False, schema='analytics')
    op.drop_column('metrics', 'type', schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='analytics')
    op.drop_index(op.f('ix_analytics_metrics_metric_type'), table_name='metrics', schema='analytics')
    op.drop_index(op.f('ix_analytics_metrics_created_at'), table_name='metrics', schema='analytics')
    op.drop_column('metrics', 'metric_type', schema='analytics')
    # ### end Alembic commands ###
